### PR TITLE
Stop reading empty ALDB (#85)

### PR DESCRIPTION
**Pull request by mstovenour**
If a device has an empty ALDB it will return one record with both
high water and unused flags.  Technically a device should return NAK
because the PLM is not in the ALDB but a 2842-222 did respond with a
0x51.  In this case _calc_load_status will never set has_all and
will never return true.

Resolves pyinsteon/pyinsteon#85

### CODE REVIEW

**Comment by teharris1** [comment]
Well, there really cannot be an empty DB since there has to be at least a record related to the modem for the modem to even be allowed to request the ALDB. So this PR would create a false exit if the last record was received before the first record (which can happen due to the way pyinsteon queries all records first, then individual records if needed).

**Comment by mstovenour** [comment]
Good catch on the flaw in the PR.  I'll submit another one with a small correction.  I'm reproducing the conditions so I can test the new change.

Below is proof that there are exceptions to the rule that you can't talk to an I2CS with an empty ALDB.  All I did was factory reset the motion sensor to reproduce this again.  Like I said in the issue write up, this is a corner case but none the less, this is what I found when I upgraded to this library.  The motion sensor was working just fine on the old library; now I'm burning through a battery about once a week.  The PR let pyinsteon move on to the next step where it adds the default links; much to my dismay, the motion allowed the ALDB write also.

As you can see the motion responded with one record;  0xfff with HW=true.

> 2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.messages] TX: msg_id: 0x62, address: 27755d, flags: 0x10, cmd1: 0x2f, cmd2: 0x00, user_data: 00.00.00.00.00.00.00.00.00.00.00.00.00.d1
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.protocol.messages.inbound] IN CREATE: 026227
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.protocol.messages.inbound] Full message not received
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.protocol.messages.inbound] IN CREATE: 026227755d102f0000000000000000000000000000d106
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.messages] RX: msg_id: 0x62, address: 27755d, flags: 0x10, cmd1: 0x2f, cmd2: 0x00, user_data: 00.00.00.00.00.00.00.00.00.00.00.00.00.d1, ack: 0x06
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.topics] Topic: ack.27755d.extended_read_write_aldb.direct data: {'cmd1': 47, 'cmd2': 0, 'user_data': 00.00.00.00.00.00.00.00.00.00.00.00.00.d1}
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.protocol.messages.inbound] IN CREATE: 0250
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.protocol.messages.inbound] Full message not received
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.protocol.messages.inbound] IN CREATE: 025027755d1edc30202f00
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.messages] RX: msg_id: 0x50, address: 27755d, target: 1edc30, flags: 0x20, cmd1: 0x2f, cmd2: 0x00
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.topics] Topic: 27755d.off_at_ramp_rate.direct_ack data: {'cmd1': 47, 'cmd2': 0, 'target': 1edc30, 'user_data': None, 'hops_left': 0}
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.topics] Topic: 27755d.extended_read_write_aldb.direct_ack data: {'cmd1': 47, 'cmd2': 0, 'target': 1edc30, 'user_data': None, 'hops_left': 0}
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.handlers.from_device.receive_aldb_record] ALDB Read direct message received
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.topics] Topic: handler.27755d.extended_read_write_aldb.direct data: {'ack_response': 0}
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.protocol.messages.inbound] IN CREATE: 025127
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.protocol.messages.inbound] Full message not received
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.protocol.messages.inbound] IN CREATE: 025127755d1edc30112f0000010fff000000000000000000c2
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.messages] RX: msg_id: 0x51, address: 27755d, target: 1edc30, flags: 0x11, cmd1: 0x2f, cmd2: 0x00, user_data: 00.01.0f.ff.00.00.00.00.00.00.00.00.00.c2
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.topics] Topic: 27755d.extended_read_write_aldb.direct data: {'cmd1': 47, 'cmd2': 0, 'target': 1edc30, 'user_data': 00.01.0f.ff.00.00.00.00.00.00.00.00.00.c2, 'hops_left': 0}
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.handlers.from_device.receive_aldb_record] ALDB Read direct message received
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.topics] Topic: handler.27755d.aldb_record_received.direct data: {**'memory': 4095**, 'controller': False, 'group': 0, 'target': 000000, 'data1': 0, 'data2': 0, 'data3': 0, **'in_use': False**, **'high_water_mark': True**, 'bit5': False, 'bit4': False}
2021-04-18 21:56:54 DEBUG (MainThread) [pyinsteon.topics] Topic: device_link_responder_removed.27755d data: {'controller': 27755d, 'responder': 000000, 'group': 0}
2021-04-18 21:56:56 DEBUG (MainThread) [pyinsteon.protocol.protocol] Started

**Comment by teharris1** [comment]
If I understand this correctly, the following must be true for this to happen:
1. The PLM has the device in its ALDB
2. The device does not have the PLM it its ALDB
3. The device response (inappropriately) to PLM requests

Is this correct?

**Comment by teharris1** [comment]
Thank you! I have decided to merge this change but I am still curious why the motion sensor ALDB is empty but the modem has the motion sensor reference. That is a broken link that should not exist.

**Comment by mstovenour** [comment]
I'm coming back from a long hiatus from home assistant development.  I work in the telecom industry and we all had a major FCC mandate to hit by June 30 to _hopefully_ slowdown some of the robocalling you get on your phone.  Sorry to black hole all the work you've been doing.  I'm back at it and have 6 devices to add to my network.  The Texas winter power grid event cycled power at my house every 45 minutes (45 on / 45 off) for 3 days straight.  In the process two of my devices gave up the ghost.  So now, for the first time since I abandoned misterhouse, I'll need to reprogram two very large all-link groups.  It should be a fun exercise.

To answer your question, the problem occurred because I factory reset the wireless motion.  Yes this condition should not exist but...  factory resetting a device isn't unheard of.  I'm just surprised that the device responded to the ALDB read command; that also should not happen, but it did and then the library was unable to "fix" the device ALDB because the library gave up.

**Pull request merged**
