### PR TITLE
change: await lock to async with lock and reformat, fixes breakage wh…

### PR DESCRIPTION
**Pull request by bshep**
…en moving to python 3.9

### CODE REVIEW

**Comment by bshep** [comment]
Fixes Issue #111 

Tested under HA 2021.7.1

**Comment by rlust** [comment]
Glad to see there is a fix, when will the fix be released?

**Comment by michaeldavie** [comment]
Awesome, I confirmed that this works in Home Assistant 2021.7.1 / Python 3.9 as well.

**Comment by bshep** [comment]
> Glad to see there is a fix, when will the fix be released?

whenever the maintainers merge this and in turn it is merged into HA

**Comment by teharris1** [comment]
THANK YOU!

**Comment by rlust** [comment]
I just upgraded to 2021.7.2 and it did not fix the Insteon issue. I still cannot load the Hub 2245 integration. Still says device not found.

**Pull request merged**
